USE [SMS]
GO

/****** Object:  Index [NonClusteredIndex-20221108-135901]    ******/
CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-20221108-135901] ON [dbo].[Course]
(
	[Name] ASC,
	[CreatedBy] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


