USE [SMS]
GO

/****** Object:  Index [NonClusteredIndex-20221108-141932]     AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-20221108-141932] ON [dbo].[Course]
(
	[CreatedBy] ASC,
	[Day] ASC,
	[Time] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


