USE [SMS]
GO

/****** Object:  Index [NonClusteredIndex-20221102-233123]     ******/
CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-20221102-233123] ON [dbo].[Invitation]
(
	[Teacher_ID] ASC,
	[Course_ID] ASC,
	[Student_ID] ASC,
	[Invite] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


