//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Invitation = new HashSet<Invitation>();
            this.Teach = new HashSet<Teach>();
        }
    
        public int Sysid { get; set; }
        public int Name { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Time { get; set; }
    
        public virtual Hours Hours { get; set; }
        public virtual NameOfCourse NameOfCourse { get; set; }
        public virtual Weekdays Weekdays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invitation> Invitation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teach> Teach { get; set; }
    }
}
